### ISSUE TITLE
Dial in Link for MS Teams meetings instead of video meeting

### ISSUE THREAD

**Issue by Acidham** [caleb531/open-conference-url#17] opened 2022-10-17 10:46 UTC
My calendar events, created by MS Outlook, contains links to the Video call and dial in links (https://dialin.teams.microsoft.com/..)
The workflow uses the dialin.teams.mircrosoft.com link instead of the teams.microsotf.com link. The result is that the workflow opens the page for Conference Dial In Numbers for MS Teams. 

I think it would be better to configure the link pattern instead of just the domain. Especially when an invitation contains more than just the video meeting link.

**Comment by caleb531** [comment] 2022-10-17 20:33
@Acidham The main reason I match wildcard subdomains is to future-proof the workflow for all the cases I can't think of. For example, my goal is that the workflow workflow can match ALL of the following theoretical cases without additional configuration:

- `zoom.us`
- `us02web.zoom.us`
- `yourcompany.zoom.us`
- `meet.google.com`
- `hangouts.google.com`
- `teams.microsoft.com`

However, you do have a valid use case here, and I have been thinking in the back of my head about an optimal solution. Here are a couple I came up with:

## Option 1: Do not match nested subdomains

Currently, my wildcard domain matching logic matches not just `zoom.us` and `*.zoom.us`, but `*.*.zoom.us` and `*.*.*.zoom.us` as well. However, in practice, I have not encountered a conference URL with more than one subdomain component (e.g. *.*.zoom.us).

This approach would be backwards-compatible in that users would only need to update the workflow to take advantage of this—no additional configuration required. The downside is that it makes an assumption about the structure of every conference URL.

## Option 2: Allow asterisk wildcards in "Conference Domains" setting

The other option is to change the "Conference Domains" setting to require explicit matching of subdomains, which could be specified as a hardcoded string (e.g. `teams.microsoft.com`) and/or with the `*` operator (e.g. `*.microsoft.com`).

This approach is backwards-incompatible because now, `zoom.us` would only match the apex domain (i.e. `https://zoom.us`) but not any subdomains (i.e. `us02web.zoom.us`). This means the user's existing value for the "Conference Domains" setting would not be compatible. However, this approach would allow greater flexibility because it gives control to the user over how general or specific the matching is.

Anyway, that is my thinking-out-loud. Please let me know if you have any comments or feedback about the possible directions.

**Comment by caleb531** [comment] 2022-10-17 23:02
@Acidham That's an interesting thought, but since domain names often consist of `.` characters, that would require escaping `.` with a backslash to create literal `.`'s because of the special meaning `.` takes on in a regex context.

Therefore, I would agree about Option 1, as I feel it's the past of least resistance (i.e. no breaking changes, and requires tweaking only one line of code). I will begin working on this soon, and release it as part of the v5.2.0 release.

**Comment by caleb531** [comment] 2022-11-26 02:30
@Acidham Sorry, forgot to follow up on this: this should be fixed now in the latest release (v5.2.0). Please give it a go and let me know how it works:

https://github.com/caleb531/open-conference-url/releases/tag/v5.2.0

**Comment by Acidham** [comment] 2022-11-26 07:21
Hi @caleb531 new version still opens DIal-in page instead of the the MS Teams meeting.

**Comment by caleb531** [comment] 2022-11-26 18:51
@Acidham Yeah, it looks like the code I intended to implemented is in v5.2.0, however if you have `teams.microsoft.com`, then my algorithm will match optional subdomains off of _that_. Meaning that `dialin.teams.microsoft.com` still matches.

You _may_ be able to fix by changing your **Conference Domains** configuration to match `microsoft.com` instead of `teams.microsoft.com`. Of course, that has the potential to match other undesired `*.microsoft.com` domains, so I ultimately may need to adopt the above Option 2 in a future v6 release of the workflow.

**Comment by caleb531** [comment] 2022-11-27 04:08
Okay, I have done some tweaking of the code and configuration to allow for wildcard matching in the "Conference Domains" list (via `*`). For example, the following are valid:

- `zoom.us`
- *.zoom.us`
- `teams.microsoft.com`
- `*.webex.com`
- `*.teams.us02web.whatever.com`

Please see the attached ZIP of the beta workflow below. The new defaults should apply automatically when you install it over your current installation of the workflow, unless you make changes during the installation process.

Anyway, please give it a try and let me know what you think!

[Open Conference URL.zip](https://github.com/caleb531/open-conference-url/files/10097495/Open.Conference.URL.zip)

**Comment by Acidham** [comment] 2022-11-27 10:29
No luck. The URL that it should match starts with `https://teams.microsoft.com/l/meetup-join/19%3ameeting_MzA4ZjVlMmUtYTM0….`

FYI: But in the meantime I implemented my own workflow with iCalBuddy since they upgraded for M1 CPU ;) My regexp looks like: `re.findall(r'(https:\/\/teams\.microsoft\.com.*meetup-join.*)(>)', event)` and it works.

Still happy to perform further tests on your workflow!

**Comment by caleb531** [comment] 2022-11-27 18:10
@Acidham Weird.. I created a test event with the URL you provided, and it is correctly parsed on my end. I've attached my test calendar event for reference (you may need to tweak the time depending on your timezone).

[Test Event.ics.zip](https://github.com/caleb531/open-conference-url/files/10098912/Test.Event.ics.zip)

Also, can you please send me the current value of the "Conference Domains" configuration on your end? Here's the default value (what I have on my end):

> *.zoom.us, zoom.us, meet.google.com, hangouts.google.com, teams.microsoft.com, gotomeeting.com, *.gotomeeting.com, webex.com, *.webex.com, uberconference.com

**Comment by Acidham** [comment] 2022-11-27 21:34
Conference Domain Config String: `teams.microsoft.com,zoom.us,meet.google.com,hangouts.google.com,uberconference.com,teams.microsoft.com,gotomeeting.com,webex.com`

Here you can see the full text of the MS Teams meeting:

```________________________________________________________________________________
Microsoft Teams meeting
Join on your computer, mobile app or room device
Click here to join the meeting<https://teams.microsoft.com/l/meetup-join/19%3ameeting_Mza4ZjVlMmUaYTM0Zi0Y1LWFkOWUtNGNhNjkxM2VhYzRj%40thread.v2/0?context=%7b%22Tid%22%3a%22b1b5a-7b33-4387-94ae-d2c178decee1%22%2c%22Oid%22%3a%2296da22de-4c1b-487e-a71c-5a023d5628202%7d>
Meeting ID: 3333333
Passcode: dddd
Download Teams<https://www.microsoft.com/en-us/microsoft-teams/download-app> | Join on the web<https://www.microsoft.com/microsoft-teams/join-a-meeting>
Join with a video conferencing device
12373132324@teams.bjn.vc
Video Conference ID: 13333333
Alternate VTC instructions<https://dialin.bluejeans.com/teams?key=1283744&conf=1172332&domain=teams.bjn.vc>
Or call in (audio only)
+41 43 226 95 56,,17327071#<tel:+432169556,,1737071#>   Germany, Berling (Berlin)
Phone Conference ID: 333 437 34#
Find a local number<https://dialin.teams.microsoft.com/8781314-dca4-43db-94de-ade77dd27ef0?id=1734773321> | Reset PIN<https://dialin.teams.microsoft.com/usp/pstnconferencing>
[https://www.globe.com/content/da/cd/images/shared/global/Globe_Corporate_Horizontal_Lockup_Red_RGB_30px_high.png]
For Globe Conference Rooms, invite or forward your meeting to the conference room and use One Button to Join
Learn More<https://akas.ms/JoinTeamsMeeting> | Meeting options<https://teams.microsoft.com/meetingOptions/?organizerId=96da2323e-4c1b-487e-a71c-5a023d562820&tenantId=fa7b1b5a-7b34-4387-223ae-d2c178decee1&threadId=19_meeting_Mad4ZjVl223tYTM0Zi00NmasfLWFkOWUtNGNhNjkxM2VhYzRj@thread.v2&messageId=0&language=en-US>
________________________________________________________________________________```

**Comment by caleb531** [comment] 2022-11-27 22:36
@Acidham Thanks for providing that! It has helped me to identify the issue.

So currently, the regex I am using assumes that there are no periods in the URL. I added this restriction back in a38181974011c834eff7c63a320d9ef173e3e2b3 because some static file URLs (e.g. favicon.png) where showing up in calendar invites, and I wanted to exclude those.

However, buried in your true Teams URL is a period (`thread.v2`), and this is causing the URL _not_ to be recognized by the workflow. The fix for this _may_ mean modifying the regex to support periods again, but I may be able to instead update the regex to achieve the best of both worlds.

I plan to write out some automated tests to handle these cases and inform the solution, so stay tuned!

**Comment by Acidham** [comment] 2022-11-28 17:48
Ok great! Let me know as soon you have something to test

**Comment by caleb531** [comment] 2022-11-29 22:48
@Acidham Attached below is the latest beta. I've completely rewritten the algorithm for matching conference URLs to be much more flexible.

[ocu-6.0.0-beta.2.alfredworkflow.zip](https://github.com/caleb531/open-conference-url/files/10117910/ocu-6.0.0-beta.2.alfredworkflow.zip)

I am also working on a comprehensive series of automated tests to prevent future regressions for a wide variety of test cases (you can follow the [v6 branch](https://github.com/caleb531/open-conference-url/tree/v6) for updates). Your sample meeting URLs served as the basis for that, so thank you again.

**Comment by Acidham** [comment] 2022-11-30 09:44
Now it works and opens the MS Teams meeting in the browser. 

One suggestion that you could think about: When you replace `https` with `msteams` it opens directly in the MS Teams Client. A User Config would be great and let user decide to open in browser or MS Teams.

**Comment by caleb531** [comment] 2022-11-30 19:00
@Acidham That's a great idea. I already have a similar configuration option for the Zoom protocol (`zootmtg:`). However, in the case of Zoom, it's not as simple as _just_ replacing `https://` with `zoommtg:`—a few other changes to the URL need to be made:

```python
@staticmethod
def convert_zoom_url_to_direct(zoom_url):
    zoom_url = re.sub(r'https://', 'zoommtg://', zoom_url)
    zoom_url = re.sub(r'/j/', '/join?action=join&confno=', zoom_url)
    zoom_url = re.sub(r'\?pwd=', '&pwd=', zoom_url)
    return zoom_url
```

Are there similar URL tweaks I need to make when converting to an `msteams:`-protocol URL?

**Comment by Acidham** [comment] 2022-11-30 19:04
in my implementation with iCalBuddy I am just replacing `https` with `msteams` and it works.

**Comment by caleb531** [comment] 2022-11-30 20:12
@Acidham Alright, I think I have this working. Can you please try the latest beta and let me know what you think? I've added a new configuration option called "Use Direct Teams Links" (`use_direct_msteams`), which is enabled by default.

<img width="516" alt="Screenshot 2022-11-30 at 12 11 22 PM" src="https://user-images.githubusercontent.com/872474/204898588-b0880613-49b3-44a9-b448-2737383a13f5.png">

[open-conference-url-6.0.0-beta.4.alfredworkflow.zip](https://github.com/caleb531/open-conference-url/files/10126919/open-conference-url-6.0.0-beta.4.alfredworkflow.zip)

**Comment by Acidham** [comment] 2022-11-30 20:28
Awesome works great! Thank you for that, I tend to delete my own workflow with iCalBuddy and us yours. ;) 

You can close the case once released....

**Comment by caleb531** [comment] 2022-11-30 21:36
@Acidham Yes, I will close this issue once the final v6 release is out. I'm writing the release notes now 😀

**Comment by caleb531** [comment] 2022-11-30 22:52
Closing this issue with the just-released v6:
https://github.com/caleb531/open-conference-url/releases/tag/v6.0.0

**Closed by caleb531** 2022-11-30 22:52 UTC
Labels: bug
