### ISSUE TITLE
osascript uses 98% CPU

### ISSUE THREAD

**Issue by averkiev** [caleb531/open-conference-url#24] opened 2023-05-25 05:55 UTC
I'm using the latest build. When I type "conf" the plug-in keeps showing the "Loading..." message. Activity Monitor shows osascript consuming 98% of CPU. 

I've narrowed problem down to my work Calendar. If I exclude it, the plugin fetches events from my personal iCloud calendar without any issue. Please let me know what info is needed in order to diagnose and fix the issue.

**Comment by caleb531** [comment] 2023-05-25 23:32
@averkiev This is a duplicate of #21 (which is still open). While I don't have a fix right now, I would ask that you try the process of elimination I proposed in https://github.com/caleb531/open-conference-url/issues/21#issuecomment-1540918873:

> Given that you are seeing 100% CPU on the osascript process, I am willing to bet that you have too many events across all of your calendars, and the script (or maybe just AppleScript in general) is simply unable to handle searching through that much data (even if it's only returning events for today 🤷‍♂️).
> 
> How many calendars do you have configured on your machine? Does it make any difference if you specify all of those calendar events by name? If not, I wonder if a process-of-elimination approach would help, whereby you add/remove calendars from your workflow's "Calendars" field until you identify which calendar is causing the bottleneck.

But anyway, will repost your initial message over on that issue thread. Closing this one, but please post any updates there.

**Closed by caleb531** 2023-05-25 23:32 UTC
