### ISSUE TITLE
Coudn't add permission on macOS Sonoma

### ISSUE THREAD

**Issue by elephant87** [caleb531/open-conference-url#27] opened 2023-10-02 06:54 UTC
Hi
I tried to use your workflow, but on the step to give permissions for the workflow I am not able to do it. I just don't see alfred in the calendar's permission options
<img width="1027" alt="Screenshot 2023-10-02 at 08 53 37" src="https://github.com/caleb531/open-conference-url/assets/2355960/54f92c90-1a3e-4c86-a233-6d5e8a747fe8">

**Comment by tasbouz** [comment] 2023-10-03 07:22
@caleb531 Upon running the `conf` keyword the following message comes up:

<img width="418" alt="Screenshot 2023-10-03 at 09 17 25" src="https://github.com/caleb531/open-conference-url/assets/23252152/b3e3fbb7-df3e-4116-8634-d73bd2d13eeb">

And when I click `OK` it opens the the `Privacy & Security` panel in `Settings` but no option to add Alfred is given.

<img width="496" alt="image" src="https://github.com/caleb531/open-conference-url/assets/23252152/f207608a-c5d2-4836-b153-717d2bac565f">

I recall that in previous macOS there were options to manually add application in `Privacy & Security` but in Sonoma it seems that this option is not there anymore. Maybe a solution is to make Alfred ask for calendar permissions directly (and not through a workflow) ?

**Comment by elephant87** [comment] 2023-10-03 18:52
> @elephant87 Hm, have you tried running the `conf` keyword at least once to see if you can trigger the macOS permission prompt within Alfred? I would think that is the only way to trigger Alfred's request for calendar access.

Yes, I  did, but unfortunately I didn't see any options to add alfred to calender as described below

**Comment by caleb531** [comment] 2023-10-04 00:50
@elephant87 @tasbouz That "Access must be given" permission prompt is a custom prompt from the default AppleScript-based mode, but you can bypass that custom prompt entirely by [using the icalBuddy integration](https://github.com/caleb531/open-conference-url#use-icalbuddy):

1. `brew install ical-buddy`
2. Enable the "Use icalBuddy" setting in the [workflow configuration](https://www.alfredapp.com/help/workflows/user-configuration/)

This should also be a little more performant as well when fetching events. But in the meantime, please try the below beta version of the workflow (which has the custom prompt removed) to see if that fixes the default (non-icalBuddy) mode:

https://github.com/caleb531/open-conference-url/releases/tag/v7.1.2-beta.1

**Comment by tasbouz** [comment] 2023-10-04 04:50
@caleb531 Tried the beta version. I don't get the prompt anymore, however I don't think the workflow can actually see the calendars. I created an event in my calendar to check it out however it could not find it:

```
[06:48:32.845] Open Conference URL[Script Filter] Queuing argument '(null)'
[06:48:33.282] Open Conference URL[Script Filter] Script with argv '(null)' finished
[06:48:33.289] Open Conference URL[Script Filter] {
  "items": [
    {
      "title": "No Results",
      "subtitle": "No meetings for today",
      "valid": "no"
    }
  ]
}
```

**Comment by elephant87** [comment] 2023-10-04 06:39
yes, the same behavior after updated to beta. I  definitely has meetings today, but workflow doesn't see it

**Comment by caleb531** [comment] 2023-10-04 22:32
@elephant87 Well, the workflow is designed to only show calendar events with a Zoom/Meet/Teams URL somewhere in the invite. If a calendar event has no meeting URL, it will **not** be counted.

I'm still looking into this, so please bear with me! But I definitely want to get it fixed if I can!

**Comment by caleb531** [comment] 2023-10-04 22:49
@elephant87 @tasbouz Good news! I figured out the issue, and was able to replicate the macOS permissions prompt for the default AppleScript-based mode. Please try the following beta and let me know how it works for you:

https://github.com/caleb531/open-conference-url/releases/tag/v7.1.2-beta.2

Here's the prompt I received. There's still an issue with the prompt not triggering for the icalBuddy mode, but it should be fixed for the default AppleScript mode:
<img width="352" alt="Screenshot 2023-10-04 at 3 45 51 PM" src="https://github.com/caleb531/open-conference-url/assets/872474/63580620-2c0b-4c6d-b2a2-5c70f80475af">

**Comment by elephant87** [comment] 2023-10-05 06:18
yes-yes-yes

it works now as a charm!

**Comment by elephant87** [comment] 2023-10-05 06:56
Thank you very much!

**Comment by tasbouz** [comment] 2023-10-05 10:06
It works! You're the best.

**Comment by caleb531** [comment] 2023-10-05 20:08
Aw thanks for the kind words! Glad the workflow is working well now.

And with that, I've just pushed the stable v7.1.2 release (same contents as beta 2, but just in case you want to be on a stable release with a seal of approval:

https://github.com/caleb531/open-conference-url/releases/tag/v7.1.2

Since the issue is resolved, I'll be closing this thread now. But please reach out if you run into any more snags!

**Closed by caleb531** 2023-10-05 20:08 UTC
Labels: bug
