### ISSUE TITLE
Not showing results, osascript at 100% CPU when calendar name list is empty

### ISSUE THREAD

**Issue by dzdora** [caleb531/open-conference-url#21] opened 2023-01-26 12:36 UTC
Versions 6.0.1 and 6.0.0 (Alfred 5) don't show me results unless I specify calendar names to parse. The issue seems to be that  `return calendar.get_event_dicts(prefs['calendar_names'])` never returns anything when the calendar list is empty? 

The workaround would be to specify the calendar names, but the Workflow does not seem to recognize any iCloud calendar names. I added the same event with to multiple calendars to test this and it only recognizes the Google calendars and the calendars added via Exchange.

**Comment by caleb531** [comment] 2023-01-27 05:31
@dzdora How odd, because I have a mix of iCloud and Exchange calendars, and they all show up, and my **Calendar Names** field is blank. Regardless, I definitely want to figure out the root of your particular issue.

What happens when you run `conf` when an expected event doesn't show up? Does Alfred return a "No Results" item? Do you get Alfred's fallback searches (like Google)? Or do you get nothing at all?

Also, what is your selected system language?

**Comment by caleb531** [comment] 2023-02-03 00:55
@dzdora Just wanted to follow up on this. Could you please provide the requested details from my previous comment?

**Comment by caleb531** [comment] 2023-02-17 23:28
@dzdora Just wanted to follow up again. Are you still experiencing this issue? If so, could you please provide the above requested details?

**Comment by coagmano** [comment] 2023-05-09 02:33
I'm getting issues leaving the calendar names config empty too.
When I run the workflow Alfred stays in the "Loading..." state and I get an `osascript` process using 100% CPU and never finishing (after several minutes)
Debugger only shows `[11:32:27.457] Open Conference URL[Script Filter] Queuing argument '(null)'`

Supplying the name of a google or iCloud (or both) to the config works for me

Tried running the applescript directly and it never completes either, so issue is probably in there

**Comment by caleb531** [comment] 2023-05-09 21:31
@coagmano Given that you are seeing 100% CPU on the `osascript` process, I am willing to bet that you have too many events across all of your calendars, and the script (or maybe just AppleScript in general) is simply unable to handle searching through that much data (even if it's only returning events for today 🤷‍♂️).

How many calendars do you have configured on your machine? Does it make any difference if you specify _all_ of those calendar events by name? If not, I wonder if a process-of-elimination approach would help, whereby you add/remove calendars from your workflow's "Calendars" field until you identify which calendar is causing the bottleneck.

**Comment by coagmano** [comment] 2023-05-09 22:16
It's quite possible. I think I'm subscribed to some online calendars but have them hidden.

We'll see how it goes when I specify all my normal calendars

**Comment by caleb531** [comment] 2023-05-25 23:36
@coagmano Just wanted to ask for an update. User @averkiev is experiencing the same issue (via #24, which I am consolidating into this one thread):

> I'm using the latest build. When I type "conf" the plug-in keeps showing the "Loading..." message. Activity Monitor shows osascript consuming 98% of CPU.
> 
> I've narrowed problem down to my work Calendar. If I exclude it, the plugin fetches events from my personal iCloud calendar without any issue. Please let me know what info is needed in order to diagnose and fix the issue.

I would still love to figure out how to solve this, but I will still need both of your help to do so. Can you each please try the process-of-elimination troubleshooting I mentioned above (https://github.com/caleb531/open-conference-url/issues/21#issuecomment-1540918873) and let me know what you find? (and thank you in advance!)

**Comment by averkiev** [comment] 2023-05-26 00:33
Hi @caleb531 , as I wrote in my bug report, my work calendar is causing the issue. And yes, every day has at least 10 entries, and quite often more than that. I've tested with my personal calendar, which barely has a couple of entries per week, and the plugin worked just fine.

**Comment by caleb531** [comment] 2023-05-29 02:22
@averkiev I see. Out of curiosity, if you install icalBuddy (`brew install ical-buddy` if you have [Homebrew](https://brew.sh/)), try running the following in your Terminal:

```sh
time icalBuddy eventsToday
```

How does the performance difference compare to what you are seeing with OCU? @dzdora Feel free to participate in this experiment too and let me know what numbers you are getting.

If icalBuddy proves to be significantly more performant for large calendars, that should allow me to add icalBuddy as an optional method of reading the calendar data. In other words, I am thinking that the workflow would still use the AppleScript by default, but users with large calendars could simply install icalBuddy and gain an instant performance boost.

But I don't want to get ahead of myself, so please let me know how icalBuddy compares to the AppleScript currently part of the workflow. No need for hard numbers or benchmarks, just please test between the two enough to get a general sense of how icalBuddy compares.

**Comment by averkiev** [comment] 2023-06-22 01:03
> @averkiev I see. Out of curiosity, if you install icalBuddy (`brew install ical-buddy` if you have [Homebrew](https://brew.sh/)), try running the following in your Terminal:
> 
> ```shell
> time icalBuddy eventsToday
> ```
> 
> How does the performance difference compare to what you are seeing with OCU? @dzdora Feel free to participate in this experiment too and let me know what numbers you are getting.

@caleb531 
time icalBuddy eventsToday works fine. It instantly retrieves the today's events and there is no spike in the CPU usage.

**Comment by caleb531** [comment] 2023-06-22 01:42
@averkiev Excellent! With that, I am persuaded to begin development on a system for intelligently sourcing calendar data from icalBuddy (for those who have it installed via Homebrew).

**Comment by caleb531** [comment] 2023-06-24 17:39
Update: Development is off to a good start! If you're interested, you can follow my progress on the [v7 branch](https://github.com/caleb531/open-conference-url/tree/v7).

So far, I have built the infrastructure and written the logic to fetch and parse event data from icalBuddy. Next, I will be writing the automated tests to ensure that the parsing logic produces the correct results.

**Comment by caleb531** [comment] 2023-06-25 02:55
@averkiev @coagmano @dzdora @spebaker Good news! I've just released a beta version with the new feature. Please see the official v7.0.0-beta.1 release page (link below) for the download link and instructions to enable the icalBuddy integration.

The important thing is that **even if you have icalBuddy installed, you must also enable the new "Use icalBuddy for sourcing event data" configuration option in the workflow's Configuration area**.

https://github.com/caleb531/open-conference-url/releases/tag/v7.0.0-beta.1

<img width="509" alt="Screenshot 2023-06-24 at 7 54 01 PM" src="https://github.com/caleb531/open-conference-url/assets/872474/815c17b2-6861-4773-8e76-d635f6c6b9cc">

**Comment by averkiev** [comment] 2023-06-26 01:02
@caleb531 No events are being returned. Here is a link to a video recording (the link will expire in 6 days):
[](https://filebin.net/renjdopwbrcvsdei)

**Comment by caleb531** [comment] 2023-06-26 20:38
@averkiev Ah, my apologies. There was a bug related to date parsing, which was causing the workflow to error out. Please try v7.0.0-beta.2:

https://github.com/caleb531/open-conference-url/releases/tag/v7.0.0-beta.2

**Comment by averkiev** [comment] 2023-06-27 00:39
Hi @caleb531 , with the Beta2, I'm seeing the same behavior - no events are being shown.

**Comment by caleb531** [comment] 2023-06-27 00:49
@averkiev If you are seeing your fallback searches (like Google or Amazon), that means the workflow is erroring.

Can you please check the Workflow Debugger panel (and run the workflow again) to see if there are any errors?

<img width="197" alt="Screenshot 2023-06-26 at 5 46 55 PM" src="https://github.com/caleb531/open-conference-url/assets/872474/d84a6c85-1b41-48fb-b4c7-e5d099f2007b">
<img width="852" alt="Screenshot 2023-06-26 at 5 46 52 PM" src="https://github.com/caleb531/open-conference-url/assets/872474/650fb834-a852-4f29-8149-7cc7ed9b79ce">

**Comment by averkiev** [comment] 2023-06-27 00:54
@caleb531 pls see below:
```
  File "/Users/abc/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3B9921BA-22A8-40E5-B6CC-713AEFD0080F/ocu/event.py", line 84, in parse_datetime
    return datetime.strptime(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'T00:00' does not match format '%Y-%m-%dT%H:%M'
```

**Comment by caleb531** [comment] 2023-06-27 04:11
@averkiev Okay, while I haven't been able to reproduce that precise error, I did find some places for improvement in the date-parsing logic. Namely, handling of all-day events that span multiple days, and logic to ensure that the dates are never empty (here's hoping, anyway 😅).

Please try v7.0.0-beta.3 and let me know how it works. Again, if you do not see any results, please open the debugger, run the workflow again, and sent me the error output:
https://github.com/caleb531/open-conference-url/releases/tag/v7.0.0-beta.3

**Comment by averkiev** [comment] 2023-06-27 04:34
@caleb531 , unfortunately the problem remains, but the error is slightly different this time

```
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '415875T00:00' does not match format '%Y-%m-%dT%H:%M'
```

**Comment by caleb531** [comment] 2023-06-28 03:02
@averkiev So I've been mulling over how it's possible you could be getting an integer as the date when I am explicitly passing the date and time formats.

Could you please run the following command in your Terminal and send me the output? This will output the dates/times of the current day's events from your calendar—no titles or URLs will be outputted.

```sh
icalBuddy --noRelativeDates --dateFormat '%Y-%m-%d' --timeFormat '%H:%M' --noCalendarNames --includeEventProps datetime eventsToday+0
```

If you'd prefer, you can also email me the output via the link from my [Contact page](https://calebevans.me/contact).

**Comment by averkiev** [comment] 2023-06-28 03:10
@caleb531 here it is:

• 2023-06-28 at 09:30 - 10:00
• 2023-06-28 at 11:00 - 11:30
• 2023-06-28 at 12:00 - 12:30
• 2023-06-28 at 14:00 - 15:00
• 2023-06-28 at 15:00 - 15:30
• 2023-06-28 at 15:30 - 16:30
• 2023-06-28 at 16:30 - 17:00
• 2023-06-28 at 17:00 - 17:30
• 2023-06-28 at 17:30 - 18:00
• 2023-06-28 at 18:00 - 18:30
• 2023-06-28 at 18:30 - 19:00
• 2023-06-28 at 19:00 - 19:30
• 2023-06-28 at 19:15 - 19:45
• 2023-06-28 at 19:30 - 20:00
• 2023-06-28 at 19:30 - 20:00
• 2023-06-28 at 20:00 - 20:30
• 2023-06-28 at 20:30 - 21:00
• 2023-06-28 at 21:00 - 21:30
• 2023-06-28 at 21:30 - 22:30
• 2023-06-28 at 22:30 - 23:00
• 2023-06-28 at 23:00 - 2023-06-29 at 00:00

**Comment by caleb531** [comment] 2023-06-28 03:15
@averkiev Excellent, thank you! Now, for context, if you open the debugger panel and run the workflow, what error do you currently get? (so I can make sure the latest error matches the output you've just provided me)

**Comment by averkiev** [comment] 2023-06-28 03:28
@caleb531 
Actually, surprisingly, right now there is no error. The conf command shows some entries. BUT:

1. It shows past events. Right now, it is 11:25AM here, yet event at 11:00AM is shown in the list
2. Most recent event is shown at the end of the list. I think it should be the other way around: most recent event at the top

![Screen shot 2023-06-28 11 23 20](https://github.com/caleb531/open-conference-url/assets/504469/9325901f-26cb-498c-96ca-2c2042708b5d)

**Comment by caleb531** [comment] 2023-06-28 03:50
@averkiev Thank you very much for the quick feedback, _and_ for kindly sharing a peek at how the workflow is actually displaying the events for you. A few initial thoughts:

## 1. Past Events

As of version 6.2.0 of the workflow, I did tweak the behavior to show past events, because I was running into a situation was I was joining a meeting 30 minutes in (even though the configured threshold was only +/- 15 minutes), yet still wanted to see that meeting listed in the workflow so I could join easily.

> If there are no upcoming events, past events now show below the "No Upcoming Events" message (in reverse-chronological order)

## 2. Event Order

Your screenshot does seem to match the intended sorting, with events are sorted reverse-chronologically (later events at the top). HOWEVER, if the current time was approx. 11:25am at the time of capturing that screenshot, then the first two events (with the times "15:xx") should not be showing.

For example, the time where I am is 8:45pm. I have no meetings within the next 20 minutes, so my event listing appears as follows:

<img width="564" alt="Screenshot 2023-06-27 at 8 47 08 PM" src="https://github.com/caleb531/open-conference-url/assets/872474/05fd2bfc-46a6-4c2a-acb1-8f54785d87dc">

The key is that if you have similar conditions (past events, but no events within the next ~20 minutes), then you should be seeing the "No Upcoming Events / Showing events from earlier today" message as the first result (followed by the most-to-least recent listing of today's events).

**Comment by averkiev** [comment] 2023-06-28 03:56
@caleb531 , to show past 15-30min events is fine, it is a valid use case. But right now it is 11:55AM and I'm still seeing event that started at 9:30AM. Perhaps it would make sense to check the duration of past events. If event has completed, it shouldn't be shown in the list (with may be 15 min grace period).

**Comment by caleb531** [comment] 2023-06-28 21:53
@averkiev You make a compelling argument, so I have tweaked the behavior to be (more or less) what you described. Now, only recent past events show (specifically, end time < current time <= end time + threshold).

I also forgot to ask: what is your Time Threshold setting set at currently? It was still odd to me that in your earlier screenshot, the current time was 11:25, yet an event at 15:30 was showing (that should only happen if you also see the "No Upcoming Meetings  / Showing all events for today" first result).

At any rate, I've published a fourth beta of the workflow, if you'd like to give it a spin and see if the new behavior matches your expectations.
https://github.com/caleb531/open-conference-url/releases/tag/v7.0.0-beta.4

**Comment by averkiev** [comment] 2023-06-29 02:01
@caleb531 thank you for the hard work!

Time Threshold is set to 60. Yet, as I'm tesing now on B4, the conf command shows events that are 9 hours away. It seems like the Time Threshold value is being ignored.

**Comment by averkiev** [comment] 2023-06-29 05:23
@caleb531 and now, two hours later, "conf" is not showing events that are several hours away (correct behavior). I'm wondering if there some sort of caching going on.

PS: as a person who pretty much spends whole day on the calls, I would very much prefer to see the most recent upcoming event at the top of the list. Now, I need to scroll to the bottom in order to join a meeting. This is counterproductive.

**Comment by caleb531** [comment] 2023-06-29 21:26
@averkiev A few things:

## Caching

In early versions of the workflow, I did have a caching mechanism, but I stripped that out back in v4 because it was becoming more of a headache than a convenience. All that to say, the workflow no longer caches anything, and I don't _think_ icalBuddy implements any sort of caching. 🤷‍♂️

## Sorting

Regarding your sidenote: that's an interesting idea, and is one I considered adding, however I reasoned that the chronology of the sorting might be a little counterintuitive (because in your case, upcoming events would be listed chronologically top-to-bottom, but then past events would be listed reverse-chronologically (most-recent-to-oldest).

## Idea: Two Time Thresholds?

I know you said you have the time threshold set to 60 minutes. Do you think it would be useful to split that configuration option into two? That is, have one option for the 'leading' threshold before a meeting starts, and another option for the 'trailing' threshold after a meeting ends.

For example, you could see meetings which are starting no later than 15 minutes into the future, _however_ you could also see meetings which ended an hour ago.

## Finally: a quick favor

Can you please run the following in your Terminal and let me know if it matches your system's current date/time?

```sh
python3 -c 'from datetime import datetime; print(datetime.now())'
```

**Comment by averkiev** [comment] 2023-06-30 00:42
@caleb531 
**Sorting**
It should be different for past and upcoming events. First of all for the past events, I would show **only one past event** that fits in the Time Threshold (or you can have two time thresholds as per your suggestion). So there wouldn't be an issue with sorting past events. And for upcoming events the sorting should start from the most recent upcoming event.

**Idea: Two Time Thresholds?**
Yes, that could be an option

It does match the current system date/time
2023-06-30 08:41:35.868007

**Comment by caleb531** [comment] 2023-07-04 19:22
@averkiev Sorry for the late reply—it's been a busy week.

The scheme you described seems reasonable to me! I will make a note to implement this behavior, although it may take a couple weeks (with everything I have going on).

**Comment by caleb531** [comment] 2023-07-16 03:41
@averkiev Okay, thanks for waiting!

I've finally implemented the logic you described, with additional/updated unit tests to cover the new behavior, as well as type checking across the entire codebase to improve resilience.

Please try the new beta 5 and let me know how it works for you:
https://github.com/caleb531/open-conference-url/releases/tag/v7.0.0-beta.5

**Comment by averkiev** [comment] 2023-07-16 23:37
@caleb531 , thanks! I've installed the B5. The new sorting of the events is an improvement! I'll report if I discover any issues.

**Comment by averkiev** [comment] 2023-07-17 02:27
@caleb531 , I've noticed a bug. I have a meeting that starts in 5 mins. Conf doesn't show it in the list. But other meetings, later in the day, show up correctly.

**Comment by caleb531** [comment] 2023-07-17 20:35
@averkiev Weird. Maybe the event data is malformed somehow? Does the event show up if you run icalBuddy? i.e.:

```sh
icalBuddy --noRelativeDates --dateFormat '%Y-%m-%d' --timeFormat '%H:%M' --noCalendarNames --includeEventProps datetime eventsToday+0
```

**Comment by caleb531** [comment] 2023-07-26 00:49
Okay everyone, I have officially decided to release v7.0.0 stable! I felt like it was time.
https://github.com/caleb531/open-conference-url/releases/tag/v7.0.0

There have been no new bugfixes or feature changes since beta 5.

**Comment by averkiev** [comment] 2023-07-26 00:52
@caleb531 thank you for the fixes!

**Comment by caleb531** [comment] 2023-07-26 03:25
@averkiev My pleasure! And now that the icalBuddy integration seems to solve the overall performance/memory issue, I will close the issue now.

@dzdora Since you are the OP, just wanted to encourage you to try v7, enable the icalBuddy integration, and let me know how it works for you! If you (or anyone else following this thread) experience any issues, please let me know and I can reopen this issue (or create a new one) to get things fixed!
https://github.com/caleb531/open-conference-url/releases/tag/v7.0.0

**Closed by caleb531** 2023-07-26 03:25 UTC
Labels: bug

**Comment by averkiev** [comment] 2023-07-28 06:59
@caleb531 FYI I'm using the 7.0 RTM version. I've got 5+ meetings back to back with the next one starting in 2 mins. The Conf command returns "No more meetings for today"

**Comment by caleb531** [comment] 2023-08-02 02:50
@averkiev Hm, I might suggest at this point, you [reach out to me via email](https://calebevans.me/contact). These issues might be a lot easier to debug if you would be open to jumping on a Zoom call.

**Comment by coagmano** [comment] 2023-08-14 03:33
Thank you very much for all the work you put into this! 
v7 works beautifully for me and (using ical-buddy) is showing events very quickly now
